{{/* vim: filetype=helm */}}
{{- if .Values.passwords }}
apiVersion: v1
kind: Secret
metadata:
  {{- if hasKey .Values "secretsName" }}
  name: {{ .Values.secretsName }}
  {{- else }}
  name: {{ include "ps-database.fullname" . }}-secrets
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ps-database.labels" . | indent 4 }}
type: Opaque
stringData:
{{ .Values.passwords | toYaml | indent 2 }}
{{- end -}}
