apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: percona-server-mysql-operator-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-mysql-operator-orchestrator
subjects:
- kind: ServiceAccount
  name: percona-server-mysql-operator-orchestrator
